#from google.colab import drive
#drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %pip install wfdb

import numpy as np
import pandas as pd
import wfdb
import os
import ast
import matplotlib.pyplot as plt
import torch
from torch.utils.data import Dataset, DataLoader, random_split, Subset
import torchvision.models as models
from torch import nn
import torch.nn.functional as F
#from tqdm import tqdm
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay

df = pd.read_csv('/content/drive/MyDrive/ECGDataset/ptbxl_database.csv')

#Import Signals that are contained ONLY in dataframe (i.e. PT-BXL Database)
def getSignal(path):
  signal = []
  onlySignal = []
  res ='records100'
  for directory1 in sorted(os.listdir(path)):
    for directory2 in sorted(os.listdir(path + '/' + directory1)):
      if (df["filename_lr"].isin([(res + '/' + directory1 + '/' + directory2).rsplit('.', 1)[0]]).any().any() and directory2.endswith(".hea")):
        onlySignal, _ = wfdb.rdsamp((path + '/' + directory1 + '/' + directory2).rsplit('.', 1)[0])
        signal.append(onlySignal)
  return signal

signals = []
path = "/content/drive/MyDrive/ECGDataset/records100"
signals = getSignal(path)

df['scp_codes'] = df['scp_codes'].apply(ast.literal_eval)
df["Label"] = df['scp_codes'].apply(lambda x: max(x, key=x.get))

df = df.drop(['ecg_id','patient_id','age','sex','height','weight','nurse',
         'site','device','recording_date','report','heart_axis','infarction_stadium1',
         'infarction_stadium2','validated_by','second_opinion','initial_autogenerated_report',
         'validated_by_human','baseline_drift','static_noise','burst_noise','electrodes_problems',
         'extra_beats', 'pacemaker','strat_fold','filename_lr','filename_hr', 'scp_codes'], axis=1)

df

mapping = {
  "NDT": 2,
  "NST_": 2,
  "DIG": 2,
  "LNGQT": 2,
  "NORM": 0,
  "IMI": 1,
  "ASMI": 1,
  "LVH": 4,
  "LAFB": 3,
  "ISC_": 2,
  "IRBBB": 3,
  "1AVB": 3,
  "IVCD": 3,
  "ISCAL": 2,
  "CRBBB": 3,
  "CLBBB": 3,
  "ILMI": 1,
  "LAO/LAE": 4,
  "AMI": 1,
  "ALMI": 1,
  "ISCIN": 2,
  "INJAS": 1,
  "LMI": 1,
  "ISCIL": 2,
  "LPFB": 3,
  "ISCAS": 2,
  "INJAL": 1,
  "ISCLA": 2,
  "RVH": 4,
  "ANEUR": 2,
  "RAO/RAE": 4,
  "EL": 2,
  "WPW": 3,
  "ILBBB": 3,
  "IPLMI": 1,
  "ISCAN": 2,
  "IPMI": 1,
  "SEHYP": 4,
  "INJIN": 1,
  "INJLA": 1,
  "PMI": 1,
  "3AVB": 3,
  "INJIL": 1,
  "2AVB": 3,
}

df["LabelGrouped"] = df["Label"].map(mapping)
df

df["Signal"] = signals
df

df = df.dropna(ignore_index = True)
df

df["Label"].value_counts().plot(kind='bar', color='skyblue')
print(df["Label"].value_counts())
print( '\n')
plt.title('Count of Each Category')
plt.xlabel('Category')
plt.ylabel('Count')

df["LabelGrouped"].value_counts().plot(kind='bar', color='skyblue')
print(df["LabelGrouped"].value_counts())
print( '\n')
plt.title('Count of Each Category Grouped')
plt.xlabel('Category')
plt.ylabel('Count')

#Plotting Data in 1 Lead (Lead X) with Label
fig, ax = plt.subplots(figsize=(20, 5))
for i in np.arange(10):
  ax.plot(signals[i][:,4], label = df["LabelGrouped"][i])
ax.legend()
print(len(signals[i][:,4]))

class ECGDataset(Dataset):
  def __init__(self, signals, labels, train=True):
      self.signals = signals
      self.labels = torch.tensor(labels, dtype=torch.long)

  def __len__(self):
      return len(self.labels)

  def __getitem__(self, idx):
    ecg1 = self.signals[idx][:,0]
    ecg2 = self.signals[idx][:,1]
    ecg3 = self.signals[idx][:,2]
    ecg4 = self.signals[idx][:,3]
    ecg5 = self.signals[idx][:,4]
    ecg6 = self.signals[idx][:,5]
    ecg7 = self.signals[idx][:,6]
    ecg8 = self.signals[idx][:,7]
    ecg9 = self.signals[idx][:,8]
    ecg10 = self.signals[idx][:,9]
    ecg11 = self.signals[idx][:,10]
    ecg12 = self.signals[idx][:,11]
    ecg = torch.from_numpy(np.stack((ecg1, ecg2, ecg3, ecg4, ecg5, ecg6, ecg7, ecg8, ecg9, ecg10, ecg11, ecg12))).float()

    labels = self.labels[idx]

    return ecg, labels

dataset = ECGDataset(df["Signal"], df["LabelGrouped"])

splitRatio1 = [int(len(dataset)*0.8 + 1), int(len(dataset)*0.2)]
trainSignals, validationSignals = random_split(dataset, splitRatio1)

validationLoader = DataLoader(validationSignals, batch_size=128, shuffle=True, drop_last=True)

splitRatio2 = [int(len(trainSignals)*0.8 + 1), int(len(trainSignals)*0.2)]
trainSignals, testSignals = random_split(trainSignals, splitRatio2)

trainLoader = DataLoader(trainSignals, batch_size=128, shuffle=True, drop_last=True)
testLoader = DataLoader(testSignals, batch_size=len(testSignals), shuffle=True, drop_last=True)
print(len(testLoader))
print(len(testSignals))
smallDataset = torch.utils.data.Subset(trainSignals, range(20))
smallLoader = DataLoader(smallDataset, batch_size=20, shuffle=True)

class CNN(nn.Module):
  def __init__(self, in_channels, num_classes):
    super(CNN, self).__init__()

    self.features = nn.Sequential(
      nn.Conv1d(12, 32, kernel_size=7, padding=3),
      nn.ReLU(),
      nn.MaxPool1d(2),

      nn.Conv1d(32, 64, kernel_size=5, padding=2),
      nn.ReLU(),
      nn.MaxPool1d(2),

      nn.Conv1d(64, 128, kernel_size=3, padding=1),
      nn.ReLU(),

      nn.AdaptiveAvgPool1d(1)
    )

    self.classifier = nn.Linear(128, num_classes)


  def forward(self, x):
    x = self.features(x)
    x = x.squeeze(-1)
    x = self.classifier(x)
    return x

model = CNN(in_channels=12, num_classes=5)
#print(model)

criterion = torch.nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

num_epochs = 200
best_validation_loss = 100000000
for epoch in range(num_epochs):
  train_loss = 0
  validation_loss = 0
  accuracy_train = 0
  accuracy_validation = 0
  total_train = 0
  total_validation = 0


  print(f'Epoch: {epoch+1}')
  model.train()
  for i, data in enumerate(trainLoader):
    train_signal, train_label = data

    outputs = model(train_signal)
    #print(f"Outputs {outputs}")
    loss = criterion(outputs, train_label)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    train_loss += loss.item()
    #print(f"Train Loss: {loss.item():.4f}")
    #print(f"Total Train Loss: {train_loss}")
    _, predicted = torch.max(outputs,1)

    accuracy_train += accuracy_score(train_label, predicted, normalize=False)

    total_train += len(train_label)
  #print(f"Train Label {train_label}")
  #print(f"Predicted Values: {predicted}")
  model.eval()

  for i, data in enumerate(validationLoader):
    validation_signal, validation_label = data
    with torch.no_grad():

      outputs = model(validation_signal)
      #print(f"Outputs {outputs}")
      loss = criterion(outputs, validation_label)

      validation_loss += loss.item()
      #print(f"Train Loss: {loss.item():.4f}")
      #print(f"Total Validation Loss: {validation_loss}")
      _, predicted = torch.max(outputs,1)

      accuracy_validation += accuracy_score(validation_label, predicted, normalize=False)

      total_validation += len(validation_label)
  #print(f"Validation Label {validation_label}")
  #print(f"Predicted Values: {predicted}")

  if validation_loss < best_validation_loss:
    best_validation_loss = validation_loss

    # Save the model state dictionary
    torch.save(model.state_dict(), 'best_model.pth')

  #print(f'Small Accuracy: {accuracy_train/total_train}')
  #print(f'Small Avg. Loss: {train_loss/len(smallLoader)}')
  print(f'Train Accuracy: {accuracy_train/total_train}')
  print(f'Train Avg. Loss: {train_loss/len(trainLoader)}')
  print(f'Validation Accuracy: {accuracy_validation/total_validation}')
  print(f'Validation Avg. Loss: {validation_loss/len(validationLoader)}')

test_correct = 0
total_test = 0

for i, data in enumerate(testLoader):
  test_signal, test_label = data

  with torch.no_grad():
    outputs = model(test_signal)

    #print(f"Test Labels: {testLabel}")
    #print(f"Test Predicted: {predicted}")

    _, predicted = torch.max(outputs,1)
    test_correct += accuracy_score(test_label, predicted, normalize=False)
    total_test += len(test_label)
print(f'Test Accuracy: {test_correct/total_test}')

print(classification_report(test_label, predicted, target_names = ['NORM', 'MI', 'STTC', 'CD', 'HYP']))

cm = confusion_matrix(test_label, predicted)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=['NORM', 'MI', 'STTC', 'CD', 'HYP']
)

disp.plot()
plt.show()
